"""
/***************************************************************************
 Equirectangular 360
                                 A QGIS plugin
 Este plugin visualiza imagenes equirectangulares
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Luis Roberto Hernández Saucedo
        email                : roberto.hernandez@grupotum.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import sys

try:
    sys.path.append("C:\eclipse\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc")
    sys.path.append(
        "/home/fragalop/eclipse/plugins/org.python.pydev.core_8.3.0.202104101217/pysrc"
    )
except ImportError:
    None


def classFactory(iface):
    from .Geo360 import Geo360

    return Geo360(iface)